# Generated by Django 5.2.7 on 2026-06-21 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('can_login', 'Can log in to the system'), ('can_view_invitations', 'Can view invitations'), ('can_create_invitation', 'Can create invitations'), ('can_view_requests', 'Can view registration requests'), ('can_approve_request', 'Can approve registration requests'), ('can_reject_request', 'Can reject registration requests'), ('can_view_users', 'Can view users'), ('can_edit_user', 'Can edit users'), ('can_delete_user', 'Can delete users'), ('can_manage_permissions', 'Can manage user permissions'), ('can_view_students', 'Can view students'), ('can_add_student', 'Can add students'), ('can_view_student_requests', 'Can view student add requests'), ('can_approve_student_request', 'Can approve student add requests'), ('can_reject_student_request', 'Can reject student add requests'), ('can_manage_content', 'Can create and edit subject groups, lessons, and sections'), ('can_view_content', 'Can view published lessons and subject groups'), ('can_manage_grades', 'Can create, edit, and delete grades'), ('can_manage_attendance', 'Can record and edit attendance'), ('can_view_attendance', 'Can view attendance records')]},
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='student_avatars/'),
        ),
        migrations.AddField(
            model_name='student',
            name='token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.center'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invitations', to='accounts.center'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='accounts.center'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='accounts.center')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'unique_together': {('name', 'center')},
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.grade'),
        ),
        migrations.AlterField(
            model_name='studentrequest',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_requests', to='accounts.grade'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('request_approved', 'Registration Approved'), ('request_rejected', 'Registration Rejected'), ('student_approved', 'Student Approved'), ('lesson_published', 'Lesson Published'), ('attendance_recorded', 'Attendance Recorded')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
