# Generated by Django 5.2.7 on 2026-06-21 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_center_alter_customuser_options_and_more'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='assigned_students',
            field=models.ManyToManyField(blank=True, related_name='assigned_lessons', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='target_grades',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='accounts.grade'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='centers',
            field=models.ManyToManyField(blank=True, related_name='subject_groups', to='accounts.center'),
        ),
        migrations.AddField(
            model_name='subjectgroup',
            name='target_grades',
            field=models.ManyToManyField(blank=True, related_name='subject_groups', to='accounts.grade'),
        ),
        migrations.AlterField(
            model_name='lessonsection',
            name='type',
            field=models.CharField(choices=[('title', 'Title'), ('content', 'Content'), ('exercise', 'Exercise'), ('quran_display', 'Quran Display')], max_length=20),
        ),
        migrations.CreateModel(
            name='ExerciseSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answers', models.JSONField(default=dict)),
                ('score', models.PositiveIntegerField(default=0)),
                ('total', models.PositiveIntegerField(default=0)),
                ('details', models.JSONField(default=list)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(limit_choices_to={'type': 'exercise'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='content.lessonsection')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_submissions', to='accounts.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
